# Save this file as .github/workflows/gh-pages.yml

name: Deploy to GitHub Pages (Vite)

on:
push:
branches: \[ main ]
workflow\_dispatch:

permissions:
contents: read
pages: write
id-token: write

concurrency:
group: "pages"
cancel-in-progress: true

jobs:
build:
runs-on: ubuntu-latest
steps:
\- name: Checkout
uses: actions/checkout\@v4

```
  - name: Set up Node
    uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: npm

  - name: Install dependencies
    run: npm ci

  - name: Build
    run: |
      npm run build
      # Copy SPA fallback for GH Pages deep links
      cp dist/index.html dist/404.html

  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: dist
```

deploy:
needs: build
runs-on: ubuntu-latest
environment:
name: github-pages
url: \${{ steps.deployment.outputs.page\_url }}
steps:
\- name: Deploy to GitHub Pages
id: deployment
uses: actions/deploy-pages\@v4
